// <auto-generated />
namespace HomeWork29_04_19.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AddedPropertiesToRailwayCarriageAndToStateroom : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddedPropertiesToRailwayCarriageAndToStateroom));
        
        string IMigrationMetadata.Id
        {
            get { return "201904191527147_AddedPropertiesToRailwayCarriageAndToStateroom"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
